export const config = {
  siteTitle: 'CK Group — Portfolio',

  boot: {
    wordmark: 'CK Group',
  },

  profile: {
    name: 'Kristofer González',
    tagline: 'Ing. Civil de Minas · Ciberseguridad · SaaS · La Serena, Chile',
  },

  startCategory: 'live',

  categories: [
    {
      id: 'ck',
      label: 'CK Group',
      icon: 'user',
      color: 9,
      items: [
        {
          id: 'quienes',
          title: '¿Quiénes somos?',
          subtitle: 'Dos empresas, un objetivo',
          status: '—',
          tags: [],
          body: 'Desde La Serena, Chile. CK Ingeniería y Construcción SpA lleva servicios mineros e industriales. CK Inteligencia y Automatización SpA construye productos SaaS para contratistas mineros.\n\nNo hacemos servicios de desarrollo — hacemos productos. Chile primero, luego LatAm.',
        },
        {
          id: 'fundador',
          title: 'Kristofer González',
          subtitle: 'Fundador · kboost',
          status: '—',
          tags: ['Ing. Minas', 'Ciberseguridad', 'Cisco', 'Chuqui Sub'],
          body: 'Ingeniero Civil de Minas con mención en ciberseguridad. Curso Cisco, experiencia en Chuqui Sub. Programación básica, IA/ML, finanzas. 8 meses dedicado full-time a construir productos SaaS.',
        },
        {
          id: 'stack',
          title: 'Stack Preferido',
          subtitle: 'Tecnologías',
          status: '—',
          tags: ['Next.js', 'TypeScript', 'Supabase', 'Rust', 'Python'],
          body: 'Frontend: Next.js 16 + TypeScript strict + Tailwind v4 + shadcn/ui\nBackend: Supabase (Auth, Postgres RLS, Realtime), NestJS + Prisma\nMobile: React Native + Expo\nIA: Claude API (Anthropic) — OCR, chat, generación documental\nInfra: Vercel, Railway, Fly.io (scl), Coolify (VM Proxmox)',
        },
      ],
    },
    {
      id: 'live',
      label: 'LIVE',
      icon: 'cube',
      color: 3,
      items: [
        {
          id: 'cip',
          title: 'CIP',
          subtitle: 'cip.ckgroup.cl · Gestión Minera',
          status: 'LIVE',
          tags: ['Next.js 16', 'TypeScript', 'Supabase', 'Recharts'],
          body: 'Plataforma SaaS para contratistas mineros. 5 módulos activos: gestión de planilla, equipos, reportería en línea, dashboard ejecutivo y productividad. Demo con datos sintéticos + producto real en producción.',
          href: 'https://cip.ckgroup.cl',
        },
        {
          id: 'cksso',
          title: 'CK SSO System',
          subtitle: 'sso.ckgroup.cl · Autenticación + IA',
          status: 'LIVE',
          tags: ['Next.js 16', 'TypeScript', 'Supabase', 'IA'],
          body: 'Single Sign-On corporativo multi-tenant con detección de anomalías vía IA. Desarrollado con Cristofer Rivera (experto SSO). Fase 2 en producción con módulo de inteligencia artificial.',
          href: 'https://sso.ckgroup.cl',
        },
        {
          id: 'waste',
          title: 'WasteSystem',
          subtitle: 'residuos.ckgroup.cl · Gestión de Flota',
          status: 'LIVE',
          tags: ['Next.js 16', 'MapLibre', 'Framer Motion', 'Supabase'],
          body: 'Sistema de gestión de residuos industriales con tracking satelital, reportería ambiental y módulo de flota. En proceso de pivote estratégico a flota de rampas mineras.',
          href: 'https://residuos.ckgroup.cl',
        },
        {
          id: 'pyrenix',
          title: 'Pyrenix / OpenFire',
          subtitle: 'spci.ckgroup.cl · Simulación 3D',
          status: 'LIVE',
          tags: ['Next.js 16', 'Three.js', 'R3F', 'MapLibre'],
          body: 'Simulador 3D de propagación de incendios con React Three Fiber. Topografía real, datos Copernicus, modelos predictivos. Fase 0 productiva.',
          href: 'https://spci.ckgroup.cl',
        },
        {
          id: 'gestion',
          title: 'CK Gestión IA',
          subtitle: 'gestion.ckgroup.cl · ERP con IA',
          status: 'LIVE',
          tags: ['Next.js 15', 'shadcn/ui', 'Supabase', 'IA'],
          body: 'ERP inteligente para contratistas mineros. Fase 5 con módulo de compras completo: cotizaciones en UF (CK-000XX), flujo de aprobaciones, dashboard de gastos. 39 tablas en Supabase con RLS multi-tenant.',
          href: 'https://gestion.ckgroup.cl',
        },
        {
          id: 'satrisk',
          title: 'SatRisk',
          subtitle: 'Análisis Satelital · LIVE Railway',
          status: 'LIVE',
          tags: ['Python', 'FastAPI', 'WeasyPrint', 'Flow'],
          body: 'SaaS de análisis de riesgo geoespacial para faenas mineras. Generación de reportes PDF con WeasyPrint, cobro con Flow (producción real). Sprint 1 completo, LIVE en Railway.',
        },
        {
          id: 'ckgroup',
          title: 'CK Group Web',
          subtitle: 'ckgroup.cl · Corporativa',
          status: 'LIVE',
          tags: ['Astro', 'Tailwind', 'TypeScript'],
          body: 'Sitio web corporativo del holding CK Group. Landing page con información de empresas, servicios y contacto. Astro + Tailwind.',
          href: 'https://ckgroup.cl',
        },
        {
          id: 'tratalc',
          title: 'TRATALC Web',
          subtitle: 'Web Cliente Minero',
          status: 'LIVE',
          tags: ['Astro', 'Tailwind', 'TypeScript'],
          body: 'Desarrollo web para cliente del sector minero (Raúl Carrasco). Sitio profesional con información corporativa y servicios vinculados a ROV Fleet.',
        },
        {
          id: 'radar',
          title: 'Radar Licitaciones',
          subtitle: 'Scraping · VM Proxmox',
          status: 'LIVE',
          tags: ['Node.js', 'HTML', 'VM Proxmox'],
          body: 'Motor de scraping y monitoreo automatizado de licitaciones del sector minero. Agente agendado cada lunes 08:00 Chile. Corre en VM Ubuntu con Coolify.',
        },
      ],
    },
    {
      id: 'beta',
      label: 'Beta',
      icon: 'spark',
      color: 6,
      items: [
        {
          id: 'rovfleet',
          title: 'ROV Fleet',
          subtitle: 'rov-fleet.vercel.app · Gestión Marina',
          status: 'BETA',
          tags: ['Next.js', 'Supabase', 'TypeScript'],
          body: 'Plataforma de gestión integral para flotas de ROV (vehículos operados remotamente). Tracking en tiempo real, mantenimiento programado, asignación de equipos y personal. Beta LIVE con clientes reales.',
          href: 'https://rov-fleet.vercel.app',
        },
        {
          id: 'rovmobile',
          title: 'ROV Fleet Mobile',
          subtitle: 'Expo · React Native',
          status: 'BETA',
          tags: ['Expo', 'React Native', 'TypeScript'],
          body: 'App móvil para operadores de ROV en terreno. Reportes offline, checklist de mantenimiento, notificaciones push. En beta con clientes reales.',
        },
      ],
    },
    {
      id: 'demo',
      label: 'Demo',
      icon: 'cube',
      color: 7,
      items: [
        {
          id: 'coti',
          title: 'CotiLinkPro',
          subtitle: 'cotipro.ckgroup.cl · Cotizaciones',
          status: 'DEMO',
          tags: ['Next.js 14', 'NestJS', 'Prisma', 'pnpm'],
          body: 'Plataforma de cotizaciones para contratistas. Backend NestJS con Prisma ORM, frontend Next.js 14. Fundación de autenticación completa.',
          href: 'https://cotipro.ckgroup.cl',
        },
        {
          id: 'cutcall',
          title: 'CutCall',
          subtitle: 'cutcall.cl · Comunicaciones',
          status: 'DEMO',
          tags: ['Astro', 'Supabase', 'Twilio'],
          body: 'Solución para gestión de cortes de llamadas en operaciones mineras. Landing page + waitlist con Supabase y Twilio.',
          href: 'https://cutcall.cl',
        },
        {
          id: 'oxy',
          title: 'OxyWatch',
          subtitle: 'Monitoreo Ambiental',
          status: 'DEMO',
          tags: ['Next.js 16', 'TypeScript', 'Copernicus', 'Multi-tenant'],
          body: 'Dashboard de monitoreo de oxígeno y parámetros ambientales. 13 tabs funcionales, dark mode teal/navy, alarmas accionables, setpoints editables, multi-tenant con CRUD de empresas, integración Copernicus Marine.',
        },
        {
          id: 'saniops',
          title: 'SaniOps',
          subtitle: 'Saneamiento Industrial',
          status: 'DEMO',
          tags: ['Next.js 15', 'MapLibre', 'TypeScript'],
          body: 'Plataforma de gestión de operaciones de saneamiento y limpieza industrial. Tracking geoespacial con MapLibre, asignación de cuadrillas, reportería.',
        },
      ],
    },
    {
      id: 'dev',
      label: 'Desarrollo',
      icon: 'spark',
      color: 10,
      items: [
        {
          id: 'market',
          title: 'Market Pulse',
          subtitle: 'Motor Cuantitativo',
          status: 'DEV',
          tags: ['Next.js 16', 'TradingView', 'TypeScript'],
          body: 'Plataforma de análisis técnico y cuantitativo para mercados financieros. Motor de datos local con Yahoo Finance, visualización TradingView, indicadores personalizados. MVP ~70% funcional.',
        },
        {
          id: 'colapso',
          title: 'Colapso TCG',
          subtitle: 'Juego de Cartas · QRNG',
          status: 'DEV',
          tags: ['Next.js 16', 'QRNG', 'Three.js', 'TypeScript'],
          body: 'Trading Card Game con generación de números aleatorios cuánticos desde ANU (Australian National University). 21 cartas en v1.1, mecánicas asimétricas, UI cyberpunk.',
        },
        {
          id: 'singularidad',
          title: 'Singularidad',
          subtitle: 'Arte Generativo',
          status: 'DEV',
          tags: ['Vite', 'TypeScript', 'Canvas 2D', 'Web Audio'],
          body: 'Experiencia interactiva de arte generativo con Canvas 2D y Web Audio API. Visuales procedimentales sincronizadas con síntesis de sonido en tiempo real. Diseño cerrado v1.',
        },
      ],
    },
    {
      id: 'security',
      label: 'Seguridad',
      icon: 'spark',
      color: 0,
      items: [
        {
          id: 'ckvault',
          title: 'CK Vault',
          subtitle: 'Cifrado Portable · AES-256-GCM',
          status: 'LIVE',
          tags: ['Rust', 'egui/eframe', 'AES-256-GCM', 'Argon2id', 'ED25519'],
          body: 'Sistema portable de almacenamiento cifrado. Corre desde un pendrive, sin instalación. AES-256-GCM + Argon2id + firma ED25519 anti-tampering. Interfaz egui/eframe nativa, binario único ~14MB. Windows cross-compile, instalador propio con formateo FAT32. Fases 1-4 completas.',
          href: 'https://github.com/kboost/ck-vault',
        },
      ],
    },
    {
      id: 'idea',
      label: 'Ideación',
      icon: 'spark',
      color: 2,
      items: [
        {
          id: 'veho',
          title: 'VEHO',
          subtitle: 'veho.cl · Gestión Vehicular',
          status: 'IDEA',
          tags: ['React Native', 'NestJS', 'ClaveÚnica'],
          body: 'App de gestión vehicular con autenticación ClaveÚnica (gobierno de Chile). React Native + NestJS. En ideación.',
          href: 'https://veho.cl',
        },
        {
          id: 'btc',
          title: 'BTC Card',
          subtitle: 'Hardware · FROST + NFC',
          status: 'IDEA',
          tags: ['Rust', 'FROST', 'NFC', 'Hardware'],
          body: 'Tarjeta inteligente para firma de transacciones Bitcoin usando FROST (Flexible Round-Optimized Schnorr Threshold). Secure Element Infineon + NFC. Ideación activa.',
        },
      ],
    },
    {
      id: 'contact',
      label: 'Contacto',
      icon: 'mail',
      color: 11,
      items: [
        {
          id: 'email',
          title: 'Email',
          subtitle: 'Contacto directo',
          status: '—',
          tags: [],
          logo: 'gmail',
          body: 'k.gonzalezmery92@gmail.com',
          href: 'mailto:k.gonzalezmery92@gmail.com',
        },
        {
          id: 'github',
          title: 'GitHub',
          subtitle: 'kboost',
          status: '—',
          tags: [],
          logo: 'github',
          body: 'github.com/kboost — todos los repos privados',
          href: 'https://github.com/kboost',
        },
        {
          id: 'web',
          title: 'ckgroup.cl',
          subtitle: 'Sitio corporativo',
          status: '—',
          tags: [],
          body: 'Portal corporativo de CK Group con información de empresas, productos y contacto.',
          href: 'https://ckgroup.cl',
        },
      ],
    },
  ],
}

export const { siteTitle, boot, profile, startCategory, categories } = config
